spring.application.name=grocerybackend

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/grocerydb?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:groceryuser}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Root@123}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT:org.hibernate.dialect.MySQL8Dialect}

server.port=${PORT:8080}

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always